apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-prod
  namespace: argocd
  # annotations:
  #   argocd-image-updater.argoproj.io/image-list: app=gamertech1/bank-app-argo-cd
  #   argocd-image-updater.argoproj.io/app.helm.image-name: image.repository
  #   argocd-image-updater.argoproj.io/app.helm.image-tag: image.tag
  #   argocd-image-updater.argoproj.io/write-back-method: git
  #   argocd-image-updater.argoproj.io/git-branch: main
  #   argocd-image-updater.argoproj.io/app.update-strategy: newest-build
  #   argocd-image-updater.argoproj.io/git-repository: git@github.com:gamertech1/bank-app-gitops-config.git
  #   argocd-image-updater.argoproj.io/write-back-target: environments/prod/values.yaml
spec:
  project: default

  sources:
    - repoURL: git@github.com:gamertech1/bank-app-helm-config-argo-cd.git
      targetRevision: HEAD
      path: myapp/microservice-1
      helm:
        valueFiles:
          - $values/environments/prod/values.yaml

    - repoURL: git@github.com:gamertech1/bank-app-gitops-config.git
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
