apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  source:
    repoURL: git@github.com:gamertech1/bank-app-gitops-config.git
    path: environments
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      selfHeal: true
